#ifndef _SOUND_ID_H
#define _SOUND_ID_H

#define _SOUND_BASE 0

#define SOUND_BOSS_BIP (_SOUND_BASE + 0)
#define SOUND_EXPLOSION1 (_SOUND_BASE + 1)
#define SOUND_EXPLOSION2 (_SOUND_BASE + 2)
#define SOUND_EXPLOSION3 (_SOUND_BASE + 3)
#define SOUND_JUMP1 (_SOUND_BASE + 4)
#define SOUND_JUMP2 (_SOUND_BASE + 5)
#define SOUND_LASER1 (_SOUND_BASE + 6)
#define SOUND_LASER2 (_SOUND_BASE + 7)
#define SOUND_LASER3 (_SOUND_BASE + 8)
#define SOUND_LASER_CHARGE (_SOUND_BASE + 9)
#define SOUND_NO_TARGET (_SOUND_BASE + 10)
#define SOUND_PLAYER_BIP (_SOUND_BASE + 11)
#define SOUND_NOBODY_BIP (_SOUND_BASE + 12)
#define SOUND_SUCCESS (_SOUND_BASE + 13)
#define SOUND_TIME_OVER (_SOUND_BASE + 14)
#define SOUND_ZOOM_IN (_SOUND_BASE + 15)
#define SOUND_ZOOM_OUT (_SOUND_BASE + 16)
#define SOUND_INTRO (_SOUND_BASE + 17)


#endif